/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Guilherme_Maciel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelFundoPrincipal = new javax.swing.JPanel();
        jLabelAnimalRodaPe = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternaltentandodarcerto = new javax.swing.JPanel();
        jLabelLogoTitulo = new javax.swing.JLabel();
        jLabelRodaPe = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jPanelInternal = new javax.swing.JPanel();
        jButtonBuscarAnimal = new javax.swing.JButton();
        jButtonCadastrarAnimal = new javax.swing.JButton();
        jButtonCadastrarVeterinario = new javax.swing.JButton();
        jButtonCadastrarDono = new javax.swing.JButton();
        jButtonCadastrarClinica1 = new javax.swing.JButton();
        jButtonCadastrarVacinas = new javax.swing.JButton();
        regua = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemVeterinario = new javax.swing.JMenuItem();
        jMenuItemClinica = new javax.swing.JMenuItem();
        jMenuItemDono = new javax.swing.JMenuItem();
        jMenuItemAnimal = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemVacinas = new javax.swing.JMenuItem();
        jMenurelatorio = new javax.swing.JMenu();
        jMenuItemFicha = new javax.swing.JMenuItem();
        jMenuferramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanelFundoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAnimalRodaPe.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAnimalRodaPe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/rodapeanimal.jpg"))); // NOI18N

        jInternalFrameBemVindo.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrameBemVindo.setBorder(null);
        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternaltentandodarcerto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInternaltentandodarcerto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternaltentandodarcerto.setLayout(null);

        jLabelLogoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo.png"))); // NOI18N
        jPanelInternaltentandodarcerto.add(jLabelLogoTitulo);
        jLabelLogoTitulo.setBounds(0, 0, 160, 80);

        jLabelRodaPe.setText("Projeto de Empreendedorismo Análise e desenvolvimento de sistemas e administração");
        jPanelInternaltentandodarcerto.add(jLabelRodaPe);
        jLabelRodaPe.setBounds(10, 290, 510, 30);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gatocachorro.png"))); // NOI18N
        jPanelInternaltentandodarcerto.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(320, 0, 300, 160);

        jButtonFechar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar Tela");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanelInternaltentandodarcerto.add(jButtonFechar);
        jButtonFechar.setBounds(610, 10, 30, 30);

        jPanelInternal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonBuscarAnimal.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/IconBusca.png"))); // NOI18N
        jButtonBuscarAnimal.setToolTipText("Buscar Animal");
        jPanelInternal.add(jButtonBuscarAnimal);
        jButtonBuscarAnimal.setBounds(20, 50, 70, 70);

        jButtonCadastrarAnimal.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/IconPet.png"))); // NOI18N
        jButtonCadastrarAnimal.setToolTipText("Cadastrar Animal");
        jButtonCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAnimalActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadastrarAnimal);
        jButtonCadastrarAnimal.setBounds(380, 50, 70, 70);

        jButtonCadastrarVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/IconVet.png"))); // NOI18N
        jButtonCadastrarVeterinario.setToolTipText("Cadastrar Veterinário");
        jButtonCadastrarVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVeterinarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadastrarVeterinario);
        jButtonCadastrarVeterinario.setBounds(110, 50, 70, 70);

        jButtonCadastrarDono.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarDono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/iconDono.png"))); // NOI18N
        jButtonCadastrarDono.setToolTipText("Cadastrar Dono");
        jButtonCadastrarDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarDonoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadastrarDono);
        jButtonCadastrarDono.setBounds(200, 50, 70, 70);

        jButtonCadastrarClinica1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarClinica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/IconClinica.png"))); // NOI18N
        jButtonCadastrarClinica1.setToolTipText("Cadastrar Clinica");
        jButtonCadastrarClinica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClinica1ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadastrarClinica1);
        jButtonCadastrarClinica1.setBounds(290, 50, 70, 70);

        jButtonCadastrarVacinas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarVacinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/IconVacina.png"))); // NOI18N
        jButtonCadastrarVacinas.setToolTipText("Cadastrar Vacinas");
        jButtonCadastrarVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVacinasActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadastrarVacinas);
        jButtonCadastrarVacinas.setBounds(470, 50, 70, 70);

        jPanelInternaltentandodarcerto.add(jPanelInternal);
        jPanelInternal.setBounds(40, 120, 570, 170);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternaltentandodarcerto);
        jPanelInternaltentandodarcerto.setBounds(10, 0, 650, 320);

        javax.swing.GroupLayout jPanelFundoPrincipalLayout = new javax.swing.GroupLayout(jPanelFundoPrincipal);
        jPanelFundoPrincipal.setLayout(jPanelFundoPrincipalLayout);
        jPanelFundoPrincipalLayout.setHorizontalGroup(
            jPanelFundoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAnimalRodaPe)
                .addGap(90, 90, 90))
            .addGroup(jPanelFundoPrincipalLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jInternalFrameBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regua, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanelFundoPrincipalLayout.setVerticalGroup(
            jPanelFundoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelFundoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoPrincipalLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jInternalFrameBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(regua, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAnimalRodaPe)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFundoPrincipal);
        jPanelFundoPrincipal.setBounds(0, 0, 1460, 990);

        jLabelFundoTelaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFundoTelaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 920, 520);

        jMenuCadastro.setText("Cadastros");

        jMenuItemVeterinario.setText("Veterinário");
        jMenuItemVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeterinarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemVeterinario);

        jMenuItemClinica.setText("Clinica");
        jMenuItemClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClinicaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClinica);

        jMenuItemDono.setText("Dono");
        jMenuItemDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDonoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemDono);

        jMenuItemAnimal.setText("Animal");
        jMenuItemAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnimalActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAnimal);

        jMenuItemUsuario.setText("Usuário");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuario);

        jMenuItemVacinas.setText("Vacinas");
        jMenuItemVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVacinasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemVacinas);

        jMenuBar1.add(jMenuCadastro);

        jMenurelatorio.setText("Relatórios");

        jMenuItemFicha.setText("Imprimir Ficha");
        jMenurelatorio.add(jMenuItemFicha);

        jMenuBar1.add(jMenurelatorio);

        jMenuferramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Bem-vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuferramentas.add(jMenuItemBemVindo);

        jMenuBar1.add(jMenuferramentas);

        jMenusair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenusair.add(jMenuItemSair);

        jMenuBar1.add(jMenusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1392, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeterinarioActionPerformed
        FormVeterinario tela = new FormVeterinario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeterinarioActionPerformed

    private void jButtonCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAnimalActionPerformed
        FormAnimal tela = new FormAnimal();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarAnimalActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jButtonCadastrarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVeterinarioActionPerformed
        FormVeterinario tela = new FormVeterinario();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarVeterinarioActionPerformed

    private void jMenuItemDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDonoActionPerformed
        FormDono tela = new FormDono();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemDonoActionPerformed

    private void jMenuItemAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnimalActionPerformed
        FormAnimal tela = new FormAnimal();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemAnimalActionPerformed

    private void jButtonCadastrarClinica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClinica1ActionPerformed
        FormClinica tela = new FormClinica();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarClinica1ActionPerformed

    private void jButtonCadastrarVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVacinasActionPerformed
        FormVacinas tela = new FormVacinas();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarVacinasActionPerformed

    private void jButtonCadastrarDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarDonoActionPerformed
        FormDono tela = new FormDono();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarDonoActionPerformed

    private void jMenuItemClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClinicaActionPerformed
        FormClinica tela = new FormClinica();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemClinicaActionPerformed

    private void jMenuItemVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVacinasActionPerformed
        FormVacinas tela = new FormVacinas();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVacinasActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        FormUsuario tela = new FormUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarAnimal;
    private javax.swing.JButton jButtonCadastrarAnimal;
    private javax.swing.JButton jButtonCadastrarClinica1;
    private javax.swing.JButton jButtonCadastrarDono;
    private javax.swing.JButton jButtonCadastrarVacinas;
    private javax.swing.JButton jButtonCadastrarVeterinario;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabelAnimalRodaPe;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelLogoTitulo;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelRodaPe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAnimal;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemClinica;
    private javax.swing.JMenuItem jMenuItemDono;
    private javax.swing.JMenuItem jMenuItemFicha;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuItemVacinas;
    private javax.swing.JMenuItem jMenuItemVeterinario;
    private javax.swing.JMenu jMenuferramentas;
    private javax.swing.JMenu jMenurelatorio;
    private javax.swing.JMenu jMenusair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFundoPrincipal;
    private javax.swing.JPanel jPanelInternal;
    private javax.swing.JPanel jPanelInternaltentandodarcerto;
    private javax.swing.JLabel regua;
    // End of variables declaration//GEN-END:variables
}
